version: '2.1'
orbs:
  docker: circleci/docker@2.0.1
jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      #- docker/check
      - run:
          command: echo ${MY_PASS} | docker login --username AWS --password-stdin 363833884943.dkr.ecr.ap-south-1.amazonaws.com
      - run:
          command: ls
      - run:
          command: docker build -t fasal-repo .
      - run:
          command: docker tag fasal-repo:latest 363833884943.dkr.ecr.ap-south-1.amazonaws.com/fasal-repo:latest
      - run:
          command: docker push 363833884943.dkr.ecr.ap-south-1.amazonaws.com/fasal-repo:latest
      - docker/build:
          image: my_repo/orb-test
      - docker/push:
          digest-path: /tmp/digest.txt
          image: my_repo/orb-test
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
workflows:
  commit:
    jobs:
      - build-and-push
