version: '2.1'
orbs:
  docker: circleci/docker@2.0.1
jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      #- docker/check
      - run:
          name: "login to repo"
          command: echo ${MY_PASS} | docker login --username AWS --password-stdin 363833884943.dkr.ecr.ap-south-1.amazonaws.com
      
      - run:
          name: "docker build"
          command: docker build -t fasal-repo .
      - run:
          name: "docker tag"
          command: docker tag fasal-repo:latest 363833884943.dkr.ecr.ap-south-1.amazonaws.com/fasal-repo:latest
      - run:
          name: "docker push"
          command: docker push 363833884943.dkr.ecr.ap-south-1.amazonaws.com/fasal-repo:latest
      
workflows:
  commit:
    jobs:
      - build-and-push
